# Generated by Django 3.0.3 on 2020-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='img',
            field=models.FilePathField(default=1, path='/img'),
            preserve_default=False,
        ),
    ]
