# Generated by Django 3.0.3 on 2020-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('develop', models.CharField(max_length=20)),
            ],
        ),
    ]
