# Generated by Django 3.0.3 on 2020-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200204_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.FilePathField(default=1, path='/img'),
            preserve_default=False,
        ),
    ]
